
name: Update C# API Docs
on:
  push:
    branches:
      - master
      # test workflow
      - csharp-docs
  workflow_dispatch:
   inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore csharp/ApiDocs/ApiDocs.csproj
    - name: Build
      run: dotnet build csharp/ApiDocs/ApiDocs.csproj --no-restore
      # name: Serve
      # run: docfx ".\csharp\ApiDocs\docfx.json" --serve

    - name: Set commit ID
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        clean: false
    - name: Move API docs into target area
      run: |
        rm -rf docs/api/csharp
        mv csharp/ApiDocs/_site
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: gh-pages-pr-csharp-docs
        base: gh-pages
        title: '[Automated]: Update C# API docs'
        commit-message: 'Update C# API docs to commit ${{ steps.vars.outputs.sha_short }}'
        add-paths: docs/api/csharp
